#!/bin/bash

echo "SSH INIT"

cd /home/pi/lms-mario

echo "Scoring Socket Server Runnning...."
cd ui/
python -u scorer.py &> scorer.log &
cd ..

echo "Running Pacman Base Tiles...."
cd base
chmod +x exec-base
./exec-base

echo "Runnning Complete"
echo "To exit.....Please run 'killall python' in a new terminal"

sleep 100000000000000000000
